local TOCNAME,EC=...

local function langSplit(source)
	local ret={}
	for lang,pat in pairs(source) do
			ret[lang]=EC.Tool.Split(pat:lower(),",")
	end
	return ret
end

EC.PrefixTags = {"lf", "wtb", "looking for"}
-- MIGHT NEED THIS ONE LATER 
-- EC.EnchanterTags = {"enchant", "enchanter"}

-- ******IMPORTANT******
-- You can't have just a token number be part of the pattern or it will wrongly match on item links
-- ie "spellpower to weapon,40" will match LF JC [Relentless Earthstorm Diamond] due to the "40"
-- if instead of "40" it would be "+40" or "40+" thats okay
EC.RecipeTags={
	enGB = langSplit({
		-- ["Superior Wizard Oil"] = "Superior Wizard Oil",
		-- ["Superior Mana Oil"] = "Superior Mana Oil",
		["Enchant Weapon - Winters Might"] = "Enchant Weapon - Winters Might,wep,weapon,winter", -- 21931
		["Enchant Weapon - Unholy Weapon"] = "Enchant Weapon - Unholy Weapon,wep,weapon,unholy", -- 20033
		["Enchant Weapon - Superior Striking"] = "Enchant Weapon - Superior Striking,wep,weapon,strik,5", -- 20031
		["Enchant Weapon - Sunfire"] = "Enchant Weapon - Sunfire,wep,weapon,sunfire", -- 27981
		-- ["Enchant Weapon - Sunfire"] = "Enchant Weapon - Sunfire,sunfire,sun fire",
		["Enchant Weapon - Striking"] = "Enchant Weapon - Striking,wep,weapon,strik,3", -- 13693
		["Enchant Weapon - Strength"] = "Enchant Weapon - Strength,wep,weapon,str,15", -- 23799
		["Enchant Weapon - Spellsurge"] = "Enchant Weapon - Spellsurge,wep,weapon,spellsurge", -- 28003
		-- ["Enchant Weapon - Spellsurge"] = "Enchant Weapon - Spellsurge,spellsurge,spell surge",
		["Enchant Weapon - Spell Power"] = "Enchant Weapon - Spell Power,wep,weapon,sp,spell,30", -- 22749
		-- ["Enchant Weapon - Spell Power"] = "Enchant Weapon - Spell Power,30 sp,30+ sp",
		["Enchant Weapon - Soulfrost"] = "Enchant Weapon - Soulfrost,wep,weapon,soulfrost", -- 27982
		-- ["Enchant Weapon - Soulfrost"] = "Enchant Weapon - Soulfrost,soulfrost,soul frost",
		["Enchant Weapon - Potency"] = "Enchant Weapon - Potency,wep,weapon,str,20,potency", -- 27972
		-- ["Enchant Weapon - Potency"] = "Enchant Weapon - Potency,potency",
		["Enchant Weapon - Mongoose"] = "Enchant Weapon - Mongoose,wep,weapon,goose", -- 27984
		-- ["Enchant Weapon - Mongoose"] = "Enchant Weapon - Mongoose,mongoose",
		["Enchant Weapon - Minor Striking"] = "Enchant Weapon - Minor Striking,wep,weapon,strik,1", -- 7788
		["Enchant Weapon - Minor Beastslayer"] = "Enchant Weapon - Minor Beastslayer,wep,weapon,beast", -- 7786
		["Enchant Weapon - Mighty Spirit"] = "Enchant Weapon - Mighty Spirit,wep,weapon,spi,20", -- 23803
		-- ["Enchant Weapon - Mighty Spirit"] = "Enchant Weapon - Mighty Spirit,20 spirit,20+ spirit",
		["Enchant Weapon - Mighty Intellect"] = "Enchant Weapon - Mighty Intellect,wep,weapon,int,22", -- 23804
		["Enchant Weapon - Major Striking"] = "Enchant Weapon - Major Striking,wep,weapon,strik,7", -- 27967
		["Enchant Weapon - Major Spellpower"] = "Enchant Weapon - Major Spellpower,wep,weapon,sp,spell,40", -- 27975
		-- ["Enchant Weapon - Major Spellpower"] = "Enchant Weapon - Major Spellpower,40 sp,40 spell,40+ spell",
		["Enchant Weapon - Major Intellect"] = "Enchant Weapon - Major Intellect,wep,weapon,int,30", -- 27968
		-- ["Enchant Weapon - Major Intellect"] = "Enchant Weapon - Major Intellect,30 int,30+ int",
		["Enchant Weapon - Major Healing"] = "Enchant Weapon - Major Healing,wep,weapon,heal,81,80", -- 34010
		-- ["Enchant Weapon - Major Healing"] = "Enchant Weapon - Major Healing,81 heal,81+ heal",
		["Enchant Weapon - Lifestealing"] = "Enchant Weapon - Lifestealing,wep,weapon,lifesteal", -- 20032
		-- ["Enchant Weapon - Lifestealing"] = "Enchant Weapon - Lifestealing,lifesteal,life steal",
		["Enchant Weapon - Lesser Striking"] = "Enchant Weapon - Lesser Striking,wep,weapon,strik,2", -- 13503
		["Enchant Weapon - Lesser Elemental Slayer"] = "Enchant Weapon - Lesser Elemental Slayer,wep,weapon,ele", -- 13655
		["Enchant Weapon - Lesser Beastslayer"] = "Enchant Weapon - Lesser Beastslayer,wep,weapon,beast", -- 13653
		["Enchant Weapon - Icy Chill"] = "Enchant Weapon - Icy Chill,wep,weapon,chill", -- 20029
		["Enchant Weapon - Healing Power"] = "Enchant Weapon - Healing Power,wep,weapon,heal,55", -- 22750
		-- ["Enchant Weapon - Healing Power"] = "Enchant Weapon - Healing Power,55 heal,55+",
		["Enchant Weapon - Greater Striking"] = "Enchant Weapon - Greater Striking,wep,weapon,strik,4", -- 13943
		["Enchant Weapon - Greater Agility"] = "Enchant Weapon - Greater Agility,wep,weapon,20,agi", -- 42620
		-- ["Enchant Weapon - Greater Agility"] = "Enchant Weapon - Greater Agility,20 agi",
		["Enchant Weapon - Fiery Weapon"] = "Enchant Weapon - Fiery Weapon,wep,weapon,fiery,firey", -- 13898
		-- ["Enchant Weapon - Fiery Weapon"] = "Enchant Weapon - Fiery Weapon,fiery",
		["Enchant Weapon - Executioner"] = "Enchant Weapon - Executioner,wep,weapon,execut", -- 42974
		["Enchant Weapon - Demonslaying"] = "Enchant Weapon - Demonslaying,wep,weapon,demon", -- 13915
		["Enchant Weapon - Deathfrost"] = "Enchant Weapon - Deathfrost,wep,weapon,death,df", -- 46578
		["Enchant Weapon - Crusader"] = "Enchant Weapon - Crusader,wep,weapon,cru,crusader,sader", -- 20034
		-- ["Enchant Weapon - Crusader"] = "Enchant Weapon - Crusader,crusader",
		["Enchant Weapon - Battlemaster"] = "Enchant Weapon - Battlemaster,wep,weapon,battlemaster", -- 28004
		-- ["Enchant Weapon - Battlemaster"] = "Enchant Weapon - Battlemaster,battlemaster",
		["Enchant Weapon - Agility"] = "Enchant Weapon - Agility,wep,weapon,15,agi", -- 23800
		["Enchant Shield - Tough Shield"] = "Enchant Shield - Tough Shield,shield,tough", -- 27944
		-- ["Enchant Shield - Tough Shield"] = "Enchant Shield - Tough Shield,block value,18 block,18 value",
		["Enchant Shield - Superior Spirit"] = "Enchant Shield - Superior Spirit,shield,spi", -- 20016
		["Enchant Shield - Stamina"] = "Enchant Shield - Stamina,shield,stam", -- 13817
		["Enchant Shield - Spirit"] = "Enchant Shield - Spirit,shield,spi", -- 13659
		["Enchant Shield - Shield Block"] = "Enchant Shield - Shield Block,shield,block", -- 27946
		-- ["Enchant Shield - Shield Block"] = "Enchant Shield - Shield Block,shield block,15 block,block rating",
		-- ["Enchant Shield - Resistance"] = "Enchant Shield - Resistance",
		["Enchant Shield - Resistance"] = "Enchant Shield - Resistance,shield,res,all", -- 27947
		["Enchant Shield - Resilience"] = "Enchant Shield - Resilience,shield,res", -- 44383
		-- ["Enchant Shield - Resilience"] = "Enchant Shield - Resilience,res to shield,resilience to shield,12 res",
		["Enchant Shield - Minor Stamina"] = "Enchant Shield - Minor Stamina,shield,stam", -- 13378
		-- ["Enchant Shield - Major Stamina"] = "Enchant Shield - Major Stamina,stam to shield,18 stam,18+ stam,stamina to shield",
		["Enchant Shield - Major Stamina"] = "Enchant Shield - Major Stamina,shield,stam", -- 34009
		["Enchant Shield - Lesser Stamina"] = "Enchant Shield - Lesser Stamina,shield,stam", -- 13631
		["Enchant Shield - Lesser Spirit"] = "Enchant Shield - Lesser Spirit,shield,spi", -- 13485
		["Enchant Shield - Lesser Protection"] = "Enchant Shield - Lesser Protection,shield,armor", -- 13464
		["Enchant Shield - Lesser Block"] = "Enchant Shield - Lesser Block,shield,block", -- 13689
		["Enchant Shield - Intellect"] = "Enchant Shield - Intellect,shield,int", -- 27945
		-- ["Enchant Shield - Intellect"] = "Enchant Shield - Intellect,12 int to shield,12 intellect to shield",
		["Enchant Shield - Greater Stamina"] = "Enchant Shield - Greater Stamina,shield,stam", -- 20017
		["Enchant Shield - Greater Spirit"] = "Enchant Shield - Greater Spirit,shield,spi", -- 13905
		["Enchant Shield - Frost Resistance"] = "Enchant Shield - Frost Resistance,shield,res", -- 13933
		["Enchant Ring - Striking"] = "Enchant Ring - Striking,ring", -- 27920
		["Enchant Ring - Stats"] = "Enchant Ring - Stats,ring", -- 27927
		["Enchant Ring - Spellpower"] = "Enchant Ring - Spellpower,ring", -- 27924
		["Enchant Ring - Healing Power"] = "Enchant Ring - Healing Power,ring", -- 27926
		-- ["Enchant Gloves - Threat"] = "Enchant Gloves - Threat,threat",
		["Enchant Gloves - Threat"] = "Enchant Gloves - Threat,glove,hand,threat", -- 25072
		-- ["Enchant Gloves - Superior Agility"] = "Enchant Gloves - Superior Agility,superior agility,15 agi,15agi,15+ agi ",
		["Enchant Gloves - Superior Agility"] = "Enchant Gloves - Superior Agility,glove,hand,agi,15", -- 25080
		["Enchant Gloves - Strength"] = "Enchant Gloves - Strength,glove,hand,str", -- 13887
		-- ["Enchant Gloves - Spell Strike"] = "Enchant Gloves - Spell Strike,spell strike,hit to glove,hit to hand,15 hit,15 spell hit",
		["Enchant Gloves - Spell Strike"] = "Enchant Gloves - Spell Strike,glove,hand,spellstrike,spell,strike,hit", -- 33994
		["Enchant Gloves - Skinning"] = "Enchant Gloves - Skinning,glove,hand,skin", -- 13698
		-- ["Enchant Gloves - Shadow Power"] = "Enchant Gloves - Shadow Power,shadow power,20 shadow",
		["Enchant Gloves - Shadow Power"] = "Enchant Gloves - Shadow Power,glove,hand,shadow", -- 25073
		["Enchant Gloves - Riding Skill"] = "Enchant Gloves - Riding Skill,glove,hand,mount,ride,riding,speed", -- 13947
		["Enchant Gloves - Minor Haste"] = "Enchant Gloves - Minor Haste,glove,hand,haste", -- 13948
		["Enchant Gloves - Mining"] = "Enchant Gloves - Mining,glove,hand,mine,mining", -- 13612
		-- ["Enchant Gloves - Major Strength"] = "Enchant Gloves - Major Strength,major str,15 str,15+ str,str glove",
		["Enchant Gloves - Major Strength"] = "Enchant Gloves - Major Strength,glove,hand,str,15", -- 33995
		-- ["Enchant Gloves - Major Spellpower"] = "Enchant Gloves - Major Spellpower,sp to hand,20sp to glove,20 sp to glove,20+ sp to glove,20sp glove,",
		["Enchant Gloves - Major Spellpower"] = "Enchant Gloves - Major Spellpower,glove,hand,spell,sp,20", -- 33997
		["Enchant Gloves - Major Healing"] = "Enchant Gloves - Major Healing,glove,hand,heal,healing,35", -- 33999
		-- ["Enchant Gloves - Major Healing"] = "Enchant Gloves - Major Healing,35 heal,healing to glove,healing to hand,heal to glove,heal to hand",
		["Enchant Gloves - Herbalism"] = "Enchant Gloves - Herbalism,glove,hand,herb", -- 13617
		["Enchant Gloves - Healing Power"] = "Enchant Gloves - Healing Power,glove,hand,heal,healing", -- 25079
		["Enchant Gloves - Greater Strength"] = "Enchant Gloves - Greater Strength,glove,hand,str", -- 20013
		["Enchant Gloves - Greater Agility"] = "Enchant Gloves - Greater Agility,glove,hand,agi", -- 20012
		["Enchant Gloves - Frost Power"] = "Enchant Gloves - Frost Power,glove,hand,frost", -- 25074
		-- ["Enchant Gloves - Frost Power"] = "Enchant Gloves - Frost Power,frost power,20 frost",
		["Enchant Gloves - Fishing"] = "Enchant Gloves - Fishing,glove,hand,fish", -- 13620
		["Enchant Gloves - Fire Power"] = "Enchant Gloves - Fire Power,glove,hand,fire", -- 25078
		-- ["Enchant Gloves - Fire Power"] = "Enchant Gloves - Fire Power,fire power,20 fire",
		["Enchant Gloves - Blasting"] = "Enchant Gloves - Blasting,glove,hand,crit,blast", -- 33993
		-- ["Enchant Gloves - Blasting"] = "Enchant Gloves - Blasting,blasting to gloves,blasting to hands,crit to glove,crit to hand",
		["Enchant Gloves - Assault"] = "Enchant Gloves - Assault,glove,hand,ass,ap", -- 33996
		-- ["Enchant Gloves - Assault"] = "Enchant Gloves - Assault,assault to glove,assault to hand,gloves assault,glove assault,26 ap,26 attack power",
		["Enchant Gloves - Agility"] = "Enchant Gloves - Agility,glove,hand,agi", -- 13815
		["Enchant Gloves - Advanced Mining"] = "Enchant Gloves - Advanced Mining,glove,hand,mine,mining", -- 13841
		["Enchant Gloves - Advanced Herbalism"] = "Enchant Gloves - Advanced Herbalism,glove,hand,herb", -- 13868
		["Enchant Cloak - Superior Defense"] = "Enchant Cloak - Superior Defense,back,cloak,armor,superior", -- 20015
		-- ["Enchant Cloak - Subtlety"] = "Enchant Cloak - Subtlety,subtlety,2%",
		["Enchant Cloak - Subtlety"] = "Enchant Cloak - Subtlety,back,cloak,sub,threat", -- 25084
		["Enchant Cloak - Steelweave"] = "Enchant Cloak - Steelweave,back,cloak,steel", -- 47051
		-- ["Enchant Cloak - Stealth"] = "Enchant Cloak - Stealth,stealth",
		["Enchant Cloak - Stealth"] = "Enchant Cloak - Stealth,back,cloak,stealth", -- 25083
		-- ["Enchant Cloak - Spell Penetration"] = "Enchant Cloak - Spell Penetration,spell pen,pen to cloak,pen to back",
		["Enchant Cloak - Spell Penetration"] = "Enchant Cloak - Spell Penetration,back,cloak,sp,spell,pen,20", -- 34003
		["Enchant Cloak - Resistance"] = "Enchant Cloak - Resistance,back,cloak,res,all", -- 13794
		["Enchant Cloak - Minor Resistance"] = "Enchant Cloak - Minor Resistance,back,cloak,res,all", -- 7454
		["Enchant Cloak - Minor Protection"] = "Enchant Cloak - Minor Protection,back,cloak,armor,minor", -- 7771
		["Enchant Cloak - Minor Agility"] = "Enchant Cloak - Minor Agility,back,cloak,agi", -- 13419
		-- ["Enchant Cloak - Major Resistance"] = "Enchant Cloak - Major Resistance,major resis,7 resis",
		["Enchant Cloak - Major Resistance"] = "Enchant Cloak - Major Resistance,back,cloak,res,all", -- 27962
		-- ["Enchant Cloak - Major Armor"] = "Enchant Cloak - Major Armor,major armor,120 armor,120 armour,120+",
		["Enchant Cloak - Major Armor"] = "Enchant Cloak - Major Armor,back,cloak,armor,major", -- 27961
		["Enchant Cloak - Lesser Shadow Resistance"] = "Enchant Cloak - Lesser Shadow Resistance,back,cloak,res,shadow", -- 13522
		["Enchant Cloak - Lesser Protection"] = "Enchant Cloak - Lesser Protection,back,cloak,armor,lesser", -- 13421
		["Enchant Cloak - Lesser Fire Resistance"] = "Enchant Cloak - Lesser Fire Resistance,back,cloak,res,fire", -- 7861
		["Enchant Cloak - Lesser Agility"] = "Enchant Cloak - Lesser Agility,back,cloak,agi", -- 13882
		-- ["Enchant Cloak - Greater Shadow Resistance"] = "Enchant Cloak - Greater Shadow Resistance,shadow res",
		["Enchant Cloak - Greater Shadow Resistance"] = "Enchant Cloak - Greater Shadow Resistance,back,cloak,res,shadow", -- 34006
		["Enchant Cloak - Greater Resistance"] = "Enchant Cloak - Greater Resistance,back,cloak,res,all", -- 20014
		-- ["Enchant Cloak - Greater Nature Resistance"] = "Enchant Cloak - Greater Nature Resistance,nature res",
		["Enchant Cloak - Greater Nature Resistance"] = "Enchant Cloak - Greater Nature Resistance,back,cloak,res,nature", -- 25082
		-- ["Enchant Cloak - Greater Fire Resistance"] = "Enchant Cloak - Greater Fire Resistance,fire res",
		["Enchant Cloak - Greater Fire Resistance"] = "Enchant Cloak - Greater Fire Resistance,back,cloak,res,fire", -- 25081
		["Enchant Cloak - Greater Defense"] = "Enchant Cloak - Greater Defense,back,cloak,armor,greater", -- 13746
		["Enchant Cloak - Greater Arcane Resistance"] = "Enchant Cloak - Greater Arcane Resistance,back,cloak,res,arcane", -- 34005
		-- ["Enchant Cloak - Greater Arcane Resistance"] = "Enchant Cloak - Greater Arcane Resistance,arcane res",
		-- ["Enchant Cloak - Greater Agility"] = "Enchant Cloak - Greater Agility,greater agility to back,greater agility to cloak,12 agi to back,12 agi to cloak,12 agility to cloak,12 agility to back,agi to cloak,agility to cloak,agility to back",
		["Enchant Cloak - Greater Agility"] = "Enchant Cloak - Greater Agility,back,cloak,agi,12", -- 34004
		["Enchant Cloak - Fire Resistance"] = "Enchant Cloak - Fire Resistance,back,cloak,res,fire", -- 13657
		-- ["Enchant Cloak - Dodge"] = "Enchant Cloak - Dodge,dodge",
		["Enchant Cloak - Dodge"] = "Enchant Cloak - Dodge,back,cloak,dodge", -- 25086
		["Enchant Cloak - Defense"] = "Enchant Cloak - Defense,back,cloak,armor", -- 13635
		["Enchant Chest - Superior Mana"] = "Enchant Chest - Superior Mana,chest,mana,sup", -- 13917
		["Enchant Chest - Superior Health"] = "Enchant Chest - Superior Health,chest,hp,heal", -- 13858
		["Enchant Chest - Stats"] = "Enchant Chest - Stats,chest,stat", -- 13941
		-- ["Enchant Chest - Restore Mana Prime"] = "Enchant Chest - Restore Mana Prime,mp5 to chest",
		["Enchant Chest - Restore Mana Prime"] = "Enchant Chest - Restore Mana Prime,chest,mana,prime", -- 33991
		["Enchant Chest - Minor Stats"] = "Enchant Chest - Minor Stats,chest,stat", -- 13626
		["Enchant Chest - Minor Mana"] = "Enchant Chest - Minor Mana,chest,mana,min", -- 7443
		["Enchant Chest - Minor Health"] = "Enchant Chest - Minor Health,chest,hp,heal", -- 7420
		["Enchant Chest - Minor Absorption"] = "Enchant Chest - Minor Absorption,chest,abs", -- 7426
		["Enchant Chest - Mana"] = "Enchant Chest - Mana,chest,mana", -- 13607
		["Enchant Chest - Major Spirit"] = "Enchant Chest - Major Spirit,chest,spi", -- 33990
		-- ["Enchant Chest - Major Resilience"] = "Enchant Chest - Major Resilience,resil to chest,15 resil,major resilience,resil chest,15 res,15+ res,res to chest,res chest,15 resil to chest,major resil",
		["Enchant Chest - Major Resilience"] = "Enchant Chest - Major Resilience,chest,def,res,resil,resilience", -- 33992
		["Enchant Chest - Major Mana"] = "Enchant Chest - Major Mana,chest,mana,major", -- 20028
		["Enchant Chest - Major Health"] = "Enchant Chest - Major Health,chest,hp,heal", -- 20026
		["Enchant Chest - Lesser Stats"] = "Enchant Chest - Lesser Stats,chest,stat", -- 13700
		["Enchant Chest - Lesser Mana"] = "Enchant Chest - Lesser Mana,chest,mana,less", -- 7776
		["Enchant Chest - Lesser Health"] = "Enchant Chest - Lesser Health,chest,hp,heal", -- 7748
		["Enchant Chest - Lesser Absorption"] = "Enchant Chest - Lesser Absorption,chest,abs", -- 13538
		["Enchant Chest - Health"] = "Enchant Chest - Health,chest,hp,heal", -- 7857
		["Enchant Chest - Greater Stats"] = "Enchant Chest - Greater Stats,chest,stat","great,4", -- 20025
		-- ["Enchant Chest - Greater Stats"] = "Enchant Chest - Greater Stats,+4 stat,greater stat,4+ chest,4+ to chest,4 to chest,4 stat",
		["Enchant Chest - Greater Mana"] = "Enchant Chest - Greater Mana,chest,mana,great", -- 13663
		["Enchant Chest - Greater Health"] = "Enchant Chest - Greater Health,chest,hp,heal", -- 13640
		["Enchant Chest - Exceptional Stats"] = "Enchant Chest - Exceptional Stats,chest,stat","exc,6", -- 27960
		-- ["Enchant Chest - Exceptional Stats"] = "Enchant Chest - Exceptional Stats,6 stat,exceptional stats",
		["Enchant Chest - Exceptional Mana"] = "Enchant Chest - Exceptional Mana,chest,mana,exc", -- 27958
		["Enchant Chest - Exceptional Health"] = "Enchant Chest - Exceptional Health,chest,hp,heal", -- 27957
		-- ["Enchant Chest - Exceptional Health"] = "Enchant Chest - Exceptional Health,150 hp,150hp,exceptional health,health to chest",
		["Enchant Chest - Defense"] = "Enchant Chest - Defense,chest,def", -- 46594
		["Enchant Bracer - Superior Strength"] = "Enchant Bracer - Superior Strength,bracer,wrist,str", -- 20010
		["Enchant Bracer - Superior Stamina"] = "Enchant Bracer - Superior Stamina,bracer,wrist,hp,stam,health", -- 20011
		["Enchant Bracer - Superior Spirit"] = "Enchant Bracer - Superior Spirit,bracer,wrist,spi", -- 20009
		-- ["Enchant Bracer - Superior Healing"] = "Enchant Bracer - Superior Healing,healing to bracer,healing to wrist,heal to bracer,heal to wrist,superior healing bracer,30 healing to bracer,30 healing bracer,30 healing wrist,30 healing to wrist",
		["Enchant Bracer - Superior Healing"] = "Enchant Bracer - Superior Healing,bracer,wrist,healing,heal,30", -- 27911
		["Enchant Bracer - Strength"] = "Enchant Bracer - Strength,bracer,wrist,str", -- 13661
		-- ["Enchant Bracer - Stats"] = "Enchant Bracer - Stats,stats to bracer,stats to wrist",
		["Enchant Bracer - Stats"] = "Enchant Bracer - Stats,bracer,wrist,stat", -- 27905
		["Enchant Bracer - Stamina"] = "Enchant Bracer - Stamina,bracer,wrist,hp,stam,health", -- 13648
		["Enchant Bracer - Spirit"] = "Enchant Bracer - Spirit,bracer,wrist,spi", -- 13642
		-- ["Enchant Bracer - Spellpower"] = "Enchant Bracer - Spellpower,sp to wrist,sp to bracer,spell damage to wrist,spell damage to bracer,spelldamage to wrist,spelldamage to bracer,spellpower to wrist,spellpower to bracer,15sp,15 sp,bracer spell",
		["Enchant Bracer - Spellpower"] = "Enchant Bracer - Spellpower,bracer,wrist,spell,sp,15", -- 27917
		-- ["Enchant Bracer - Restore Mana Prime"] = "Enchant Bracer - Restore Mana Prime,mp5 to wrist,mp5 to bracer,restore mana prime",
		["Enchant Bracer - Restore Mana Prime"] = "Enchant Bracer - Restore Mana Prime,bracer,wrist,mana,prime", -- 27913
		["Enchant Bracer - Minor Strength"] = "Enchant Bracer - Minor Strength,bracer,wrist,str", -- 7782
		["Enchant Bracer - Minor Stamina"] = "Enchant Bracer - Minor Stamina,bracer,wrist,hp,stam,health", -- 7457
		["Enchant Bracer - Minor Spirit"] = "Enchant Bracer - Minor Spirit,bracer,wrist,spi", -- 7766
		["Enchant Bracer - Minor Health"] = "Enchant Bracer - Minor Health,bracer,wrist,hp,stam,health", -- 7418
		["Enchant Bracer - Minor Deflection"] = "Enchant Bracer - Minor Deflection,bracer,wrist,def", -- 7428
		["Enchant Bracer - Minor Agility"] = "Enchant Bracer - Minor Agility,bracer,wrist,agi", -- 7779
		["Enchant Bracer - Mana Regeneration"] = "Enchant Bracer - Mana Regeneration,bracer,wrist,regen", -- 23801
		["Enchant Bracer - Major Intellect"] = "Enchant Bracer - Major Intellect,bracer,wrist,int,12", -- 34001
		-- ["Enchant Bracer - Major Intellect"] = "Enchant Bracer - Major Intellect,12 int to wrist,12 int to bracer,major intellect to bracer,major intellect to wrist",
		["Enchant Bracer - Major Defense"] = "Enchant Bracer - Major Defense,bracer,wrist,def", -- 27906
		-- ["Enchant Bracer - Major Defense"] = "Enchant Bracer - Major Defense,12 def,def to bracer,def to wrist,defense to bracer",
		["Enchant Bracer - Lesser Strength"] = "Enchant Bracer - Lesser Strength,bracer,wrist,str", -- 13536
		["Enchant Bracer - Lesser Stamina"] = "Enchant Bracer - Lesser Stamina,bracer,wrist,hp,stam,health", -- 13501
		["Enchant Bracer - Lesser Spirit"] = "Enchant Bracer - Lesser Spirit,bracer,wrist,spi", -- 7859
		["Enchant Bracer - Lesser Intellect"] = "Enchant Bracer - Lesser Intellect,bracer,wrist,int", -- 13622
		["Enchant Bracer - Lesser Deflection"] = "Enchant Bracer - Lesser Deflection,bracer,wrist,def", -- 13646
		["Enchant Bracer - Intellect"] = "Enchant Bracer - Intellect,bracer,wrist,int", -- 13822
		["Enchant Bracer - Healing Power"] = "Enchant Bracer - Healing Power,bracer,wrist,healing,heal,24", -- 23802
		-- ["Enchant Bracer - Healing Power"] = "Enchant Bracer - Healing Power,24 healing,24 heal,healing power to wrist,healing power to bracer",
		["Enchant Bracer - Greater Strength"] = "Enchant Bracer - Greater Strength,bracer,wrist,str", -- 13939
		["Enchant Bracer - Greater Stamina"] = "Enchant Bracer - Greater Stamina,bracer,wrist,hp,stam,health", -- 13945
		["Enchant Bracer - Greater Spirit"] = "Enchant Bracer - Greater Spirit,bracer,wrist,spi", -- 13846
		["Enchant Bracer - Greater Intellect"] = "Enchant Bracer - Greater Intellect,bracer,wrist,int,7", -- 20008
		-- ["Enchant Bracer - Fortitude"] = "Enchant Bracer - Fortitude,fortitude to wrist,fortitude to bracer,12 stam to bracers,12 stam to wrist,12 stamina to wrist,12 stamina to bracer",
		["Enchant Bracer - Fortitude"] = "Enchant Bracer - Fortitude,bracer,wrist,hp,stam,health,fort", -- 27914
		["Enchant Bracer - Deflection"] = "Enchant Bracer - Deflection,bracer,wrist,def", -- 13931
		["Enchant Bracer - Brawn"] = "Enchant Bracer - Brawn,bracer,wrist,str,brawn", -- 27899
		-- ["Enchant Bracer - Brawn"] = "Enchant Bracer - Brawn,12 strength,12 str,brawn", 
		-- ["Enchant Bracer - Assault"] = "Enchant Bracer - Assault,bracers assault,assault to bracer,bracers assault,24 ap,24 attack power,ap to bracer",
		["Enchant Bracer - Assault"] = "Enchant Bracer - Assault,bracer,wrist,ass,ap", -- 34002
		-- ["Enchant Boots - Vitality"] = "Enchant Boots - Vitality,vitality to feet,vitality to boots",
		["Enchant Boots - Vitality"] = "Enchant Boots - Vitality,boot,feet,vit", -- 27948
		-- ["Enchant Boots - Surefooted"] = "Enchant Boots - Surefooted,surefoot",
		["Enchant Boots - Surefooted"] = "Enchant Boots - Surefooted,boot,feet,sure", -- 27954
		["Enchant Boots - Stamina"] = "Enchant Boots - Stamina,boot,feet,hp,stam,health", -- 13836
		["Enchant Boots - Spirit"] = "Enchant Boots - Spirit,boot,feet,spi", -- 20024
		["Enchant Boots - Minor Stamina"] = "Enchant Boots - Minor Stamina,boot,feet,hp,stam,health", -- 7863
		-- ["Enchant Boots - Minor Speed"] = "Enchant Boots - Minor Speed,minor speed,speed to boot,speed to feet",
		["Enchant Boots - Minor Speed"] = "Enchant Boots - Minor Speed,boot,feet,speed", -- 13890
		["Enchant Boots - Minor Agility"] = "Enchant Boots - Minor Agility,boot,feet,agi", -- 7867
		["Enchant Boots - Lesser Stamina"] = "Enchant Boots - Lesser Stamina,boot,feet,hp,stam,health", -- 13644
		["Enchant Boots - Lesser Spirit"] = "Enchant Boots - Lesser Spirit,boot,feet,spi", -- 13687
		["Enchant Boots - Lesser Agility"] = "Enchant Boots - Lesser Agility,boot,feet,agi", -- 13637
		["Enchant Boots - Greater Stamina"] = "Enchant Boots - Greater Stamina,boot,feet,hp,stam,health", -- 20020
		["Enchant Boots - Greater Agility"] = "Enchant Boots - Greater Agility,boot,feet,agi", -- 20023
		-- ["Enchant Boots - Fortitude"] = "Enchant Boots - Fortitude,fortitude to boots,fortitude to feet,fort to boots,fort boot,fort to feet,12 stam to boot,boots stamina",
		["Enchant Boots - Fortitude"] = "Enchant Boots - Fortitude,boot,feet,fort,hp,stam,health,12", -- 27950
		-- ["Enchant Boots - Dexterity"] = "Enchant Boots - Dexterity,dex to boots,dex to feet,12 agi to boots,12 agi to feet,12 agi boot,dexterity to boot,boots agil",
		["Enchant Boots - Dexterity"] = "Enchant Boots - Dexterity,boot,feet,dex,agi,12", -- 27951
		["Enchant Boots - Cats Swiftness"] = "Enchant Boots - Cats Swiftness,boot,feet,speed,cat,swift", -- 34007
		-- ["Enchant Boots - Cat's Swiftness"] = "Enchant Boots - Cat's Swiftness,cats,cat's,cat swift",
		["Enchant Boots - Boars Speed"] = "Enchant Boots - Boars Speed,boot,feet,speed,boars,piggy", -- 34008
		-- ["Enchant Boots - Boar's Speed"] = "Enchant Boots - Boar's Speed,boar",
		["Enchant Boots - Agility"] = "Enchant Boots - Agility,boot,feet,agi", -- 13935
		["Enchant 2H Weapon - Superior Impact"] = "Enchant 2H Weapon - Superior Impact,wep,weapon,impact,9", -- 20030
		["Enchant 2H Weapon - Savagery"] = "Enchant 2H Weapon - Savagery,wep,weapon,savag", -- 27971
		-- ["Enchant 2H Weapon - Savagery"] = "Enchant 2H Weapon - Savagery,savagery",
		["Enchant 2H Weapon - Minor Impact"] = "Enchant 2H Weapon - Minor Impact,wep,weapon,impact,2", -- 7745
		["Enchant 2H Weapon - Major Spirit"] = "Enchant 2H Weapon - Major Spirit,wep,weapon,spi,9", -- 20035
		["Enchant 2H Weapon - Major Intellect"] = "Enchant 2H Weapon - Major Intellect,wep,weapon,int,9", -- 20036
		["Enchant 2H Weapon - Major Agility"] = "Enchant 2H Weapon - Major Agility,wep,weapon,35,agi", -- 27977
		-- ["Enchant 2H Weapon - Major Agility"] = "Enchant 2H Weapon - Major Agility,35 agi,35+ agi",
		["Enchant 2H Weapon - Lesser Spirit"] = "Enchant 2H Weapon - Lesser Spirit,wep,weapon,spi,3", -- 13380
		["Enchant 2H Weapon - Lesser Intellect"] = "Enchant 2H Weapon - Lesser Intellect,wep,weapon,int,3", -- 7793
		["Enchant 2H Weapon - Lesser Impact"] = "Enchant 2H Weapon - Lesser Impact,wep,weapon,impact,3", -- 13529
		["Enchant 2H Weapon - Impact"] = "Enchant 2H Weapon - Impact,wep,weapon,impact,5", -- 13695
		["Enchant 2H Weapon - Greater Impact"] = "Enchant 2H Weapon - Greater Impact,wep,weapon,impact,7", -- 13937
		["Enchant 2H Weapon - Agility"] = "Enchant 2H Weapon - Agility,wep,weapon,25,agi", -- 27837
	}),
}
